### ISSUE TITLE
About the cosine distance calculation

### ISSUE THREAD

**Issue by Jo-wang** [mingukjang/TAST#1]
Hi,

I was going through your code on GitHub, specifically this file: [adapt_algorithms.py](https://github.com/mingukjang/TAST/blob/07d4fdf5c0eb78561d1ff1885631338c4b798a91/domainbed/adapt_algorithms.py#L294). I was wondering what does  `XX+YY+XY` do for the distance calculation. Can we simply use  `1-cosine_similarity' as the distance?

Could you shed some light on the reasoning behind this calculation? I'm interested in understanding the logic behind it.

Best regards,
JO

**Comment by mingukjang** [comment]
Thank you for your interest in our work. In many metric learning works, including prototypical network (Snell et al., 2017), the Euclidean metric and cosine similarity which normalize feature representations are commonly used to calculate the distance between features in the embedding space. Our work is inspired from these studies.
